apiVersion: v1
kind: Service
metadata:
  name: tomcatwar-loadbalancer
  labels:
    service: tomcatwar-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31445
    protocol: TCP
  selector:
    app: tomcatwar    
